### ISSUE TITLE
Pycobertura diff breaks on non-ascii characters

### ISSUE THREAD

**Issue by Herg** [SurveyMonkey/pycobertura#63]
```text
Traceback (most recent call last):
   File "/usr/local/bin/pycobertura", line 11, in <module>
     sys.exit(pycobertura())
   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
     return self.main(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
     return callback(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/pycobertura/cli.py", line 117, in diff
     report = reporter.generate()
   File "/usr/local/lib/python2.7/dist-packages/pycobertura/reporters.py", line 311, in generate
     return template.render(**render_kwargs)
   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
     return self.environment.handle_exception(exc_info, True)
   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/local/lib/python2.7/dist-packages/pycobertura/templates/html-delta.jinja2", line 79, in top-level template code
     {{ render_source(hunk) }}
   File "/usr/local/lib/python2.7/dist-packages/pycobertura/templates/macro.source.jinja2", line 15, in template
     <span class="{{ line|line_status }}">{{ line.source|escape }}</span>
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 71: ordinal not in range(128)
```

**Comment by aconrad** [comment]
Thanks for reporting, fixed in #64 and released `pycobertura==0.7.2`.
