### ISSUE TITLE
UnboundLocalError: local variable 'status' referenced before assignment

### ISSUE THREAD

**Issue by msabramo** [SurveyMonkey/pycobertura#69]
Larry got this error with ProfileWeb build 264927...

```
('pycobertura', 'diff', '-f', 'html', '-o', 'pycobertura.html', 'coverage-destination.xml', 'coverage.xml', '--source1=./destination/', '--source2=./source/')
```

```pytb
Traceback (most recent call last):
  File "/opt/webapp/pycobertura/bin/pycobertura", line 9, in <module>
    load_entry_point('pycobertura==0.7.2', 'console_scripts', 'pycobertura')()
  File "/opt/webapp/pycobertura/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/opt/webapp/pycobertura/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/opt/webapp/pycobertura/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/webapp/pycobertura/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/webapp/pycobertura/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/pycobertura/pycobertura/cli.py", line 117, in diff
    report = reporter.generate()
  File "/opt/src/pycobertura/pycobertura/reporters.py", line 284, in generate
    lines = self.get_report_lines()
  File "/opt/src/pycobertura/pycobertura/reporters.py", line 167, in get_report_lines
    class_row = self.get_class_row(class_name)
  File "/opt/src/pycobertura/pycobertura/reporters.py", line 139, in get_class_row
    missed_lines = self.differ.diff_missed_lines(class_name)
  File "/opt/src/pycobertura/pycobertura/cobertura.py", line 322, in diff_missed_lines
    for line in self.class_source(class_name):
  File "/opt/src/pycobertura/pycobertura/cobertura.py", line 381, in class_source
    line = Line(lineno, source, status, reason)
UnboundLocalError: local variable 'status' referenced before assignment
```

**Comment by aconrad** [comment]
After investigation, this may happen if the coverage report passed as first argument (`COBERTURA_FILE1`) was not generated by the source code given as `--source1`.

Closing this issue since it's a user error.
